apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-inspection-backend
  namespace: otel-inspection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-inspection-backend
  template:
    metadata:
      labels:
        app: otel-inspection-backend
    spec:
      containers:
      - name: backend
        image: rcskin/otel-inspection-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi" 