apiVersion: v1
kind: Service
metadata:
  name: otel-inspection-backend
  namespace: otel-inspection
spec:
  selector:
    app: otel-inspection-backend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP 