apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: pyapp
  labels:
    app: fastapi-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
      annotations:
        admission.datadoghq.com/python-lib.version: "v2.10.4"
        admission.datadoghq.com/enable: "true"
    spec:
      containers:
        - name: fastapi-app
          image: rcskin/fastapi-app:latest
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: REDIS_HOST
              value: "redis.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
            - name: DD_TRACE_IGNORE_RESOURCES
              value: "GET /health"
            - name: DD_LOG_INJECTION
              value: "true"
            - name: DD_VERSION
              value: "1.0.0"
          envFrom:
            - configMapRef:
                name: fastapi-config