apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-store

resources:
  - services/frontend/deploy
  - services/inventory-service/deploy

commonLabels:
  app.kubernetes.io/part-of: otel-store

patches:
  - patch: |-
      - op: add
        path: /spec/template/metadata/labels/admission.datadoghq.com~1enabled
        value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env
        value: []
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DD_ENV
          value: "otel-store"

    target:
      kind: Deployment
      name: ".*"
      namespace: otel-store
