apiVersion: v1
kind: Service
metadata:
  name: otel-inspection-frontend
  namespace: otel-inspection
spec:
  selector:
    app: otel-inspection-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 