apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: otel-store
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rcskin/otel-store-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
