apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: py-producer:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: producer-config