apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: otel-store
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: rcskin/otel-store-inventory:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_SERVICE_NAME
          value: "inventory-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://datadog-cluster-agent.datadog.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_SAMPLER_TYPE
          value: "parentbased_always_on"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage" 