apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: otel-store
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: inventory-service 